//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalletManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movement
    {
        public int id_movement { get; set; }
        public int id_wallet { get; set; }
        public string descrip { get; set; }
        public string isDebt { get; set; }
        public Nullable<int> idDeudor { get; set; }
        public decimal mount { get; set; }
        public int id_typeMovement { get; set; }
        public int id_clasification { get; set; }
    
        public virtual Clasification Clasification { get; set; }
        public virtual Person Person { get; set; }
        public virtual TypeOfMovement TypeOfMovement { get; set; }
        public virtual Wallet Wallet { get; set; }
    }
}
