//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalletManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movements
    {
        public int id_movement { get; set; }
        public int id_wallet { get; set; }
        public string descrip { get; set; }
        public string isDebt { get; set; }
        public Nullable<int> idDeudor { get; set; }
        public decimal mount { get; set; }
        public int id_typeMovement { get; set; }
        public int id_clasification { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Clasifications Clasifications { get; set; }
        public virtual Persons Persons { get; set; }
        public virtual TypeOfMovements TypeOfMovements { get; set; }
        public virtual Wallets Wallets { get; set; }
        public void ValidarMonto()
        {
            if (mount < 0)
                throw new ApplicationException("Please, enter a valid mount value");
        }
    }
}
