//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallet.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class walletManagerDBEntities : DbContext
    {
        public walletManagerDBEntities()
            : base("name=walletManagerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clasification> clasifications { get; set; }
        public virtual DbSet<fixedExpense> fixedExpenses { get; set; }
        public virtual DbSet<movement> movements { get; set; }
        public virtual DbSet<person> persons { get; set; }
        public virtual DbSet<typeOfMovement> typeOfMovements { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<wallet> wallets { get; set; }
    }
}
