//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallet.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class movement
    {
        public int id_movement { get; set; }
        public string descrip { get; set; }
        public string isDebt { get; set; }
        public Nullable<int> idDeudor { get; set; }
        public decimal mount { get; set; }
        public int id_typeMovement { get; set; }
        public int id_clasification { get; set; }
    
        public virtual clasification clasification { get; set; }
        public virtual person person { get; set; }
        public virtual typeOfMovement typeOfMovement { get; set; }
    }
}
