use WalletManagerDB
insert into users values ('gastonmastra', '123')
insert into clasifications values ('Comida','Gastos correspondientes a comidas, meriendas, etc.')
insert into clasifications values ('Salidas', 'Gastos correspondientes a salidas con los chicos, alcohol, etc.')
insert into TypeOfMovements values ('Ingresos')
insert into TypeOfMovements values ('Salidas')
insert into TypeOfMovements values ('Deudas')
insert into wallets values ('Billetera')
insert into wallets values ('Ahorros')
insert into wallets values ('MercadoPago')